<?php
/*
    *@Author: Daniel Salazar
    PHP - Random Quote Generator

*/

//Declaration global variables
$hex = '#';

// Multidimensional array of quote elements and name it quotes
//Some links to help me remember how it works multidimensional arrays
    //https://teamtreehouse.com/library/associative-arrays
    //https://teamtreehouse.com/library/multidimensional-arrays
$quotes[] = array(
    array("quote" => "Bazinga!", 
          "source" => "Sheldon Lee Cooper", "citation" => "Big Bang Theory", "tag" => "Humor"),
    array("quote" => "Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened, ambition inspired and success achieved.", 
          "source" => "Helen Keller", "tag" => "Motivational"),
    array("quote" => "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.", 
          "source" => "Albert Schweitzer", "tag" => "Motivational"),
    array("quote" => "Every problem is a gift—without problems we would not grow.", 
          "source" => "Anthony Robbins", "tag" => "Business"),
    array("quote" => "Even if you are on the right track, you’ll get run over if you just sit there.", 
          "source" => "Will Rodgers", "tag" => "Business"),  
    array("quote" => "Imagination is everything. It is the preview of life’s coming attractions.", 
          "source" => "Albert Einstein", "tag" => "Motivational"),   
    array("quote" => "For every minute you are angry you lose sixty seconds of happiness", 
          "source" => "Ralph Waldo Emerson", "tag" => "Happiness"),    
    array("quote" => "The only true wisdom is in knowing you know nothing.", 
          "source" => "Socrates", "tag" => "Wisdom"),    
    array("quote" => "Even when our eyes are closed, there's a whole world that exists outside ourselves and our dreams.",
          "source" => "Hiromu Arakawa", "citation" => "Fullmetal Alchemist, Vol. 1 (Fullmetal Alchemist, #1)", "year" => 2002, "tag" => "Manga"),
    array("quote" => "Passion is fuel for the will. Passion turns your have-to’s into want-to’s. what we accomplish in life is based less on what we want and more on how much we want it.",
          "source" => "John C. Maxwell", "citation" => "The 21 Indispensable Qualities of a Leader", "year" => 1999, "tag" => "Motivational")
);




// Function to select a random array from multiple Array.
// It needs an array as parameter
function getRandomQuote($arr) {
    // Generate and save in variable a random number between 0 and the last index in the array parameter
        // How it work rand: http://php.net/manual/en/function.rand.php
    // How to get size of Array https://www.php.net/manual/es/function.count
    $noRand = rand(0, count($arr[0])-1);

    // Save in a variable only one array from the multiple arrays
    $message = ($arr[0][$noRand]);
    // Return the SELECTED random array
    return $message;
}
 
// Function to create a random color, adapted from https://thisinterestsme.com/random-rgb-hex-color-php/
//Create a loop.
function getRandomColor(){
    //Using global variable
    global $hex;
    foreach(array('r', 'g', 'b') as $color){
        //Random number between 0 and 255.
        $val = mt_rand(0, 255);
        //Convert the random number into a Hex value.
        $dechex = dechex($val);
        //Pad with a 0 if length is less than 2.
        if(strlen($dechex) < 2){
            $dechex = "0" . $dechex;
        }
        //Concatenate each value RGB
        $hex .= $dechex;
    }
    //Retunr complete Hex color
    return $hex;
}


// Function to print in html (quote) generated by calling getRandomQuote($quotes)
function printQuote() {
    //Using global variable
    global $quotes;
    //Variable that calls the getRandomQuote() function, passing in the quotes array as an argument
    $message = getRandomQuote($quotes);
    //Initialize of required HTML string
    $htmlString = "<p class=\"quote\">" . $message["quote"] . "</p>" .
                    "<p class=\"source\">" . $message["source"];
                        
    // if the quote contains a citation value, add the proper value if not ignore
        //https://www.w3schools.com/php/func_array_key_exists.asp
    if (array_key_exists("citation", $message)){
        $htmlString.= "<span class=\"citation\">" . $message["citation"] . "</span>";
    }
    // if the quote contains a citation year, add the proper value if not ignore
    if (array_key_exists("year",$message)){
        $htmlString.=  "<span class=\"year\"></span>" . $message["year"];
    }

    // if the quote contains a tag, add the proper value if not ignore
    if (array_key_exists("tag", $message)){
        $htmlString.=  "<span class=\"year\"></span>" . $message["tag"];
    }

    // Finalize HTML string
    $htmlString .= "</p>";
    
    // Display the complete HTML string
    echo $htmlString;
 }


?>